#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef KINDREDSDKCORE_SWIFT_H
#define KINDREDSDKCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="KindredSDKCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC14KindredSDKCore9Analytics")
@interface Analytics : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
@class KindredCoreError;

SWIFT_PROTOCOL("_TtP14KindredSDKCore24AnalyticsServiceProtocol_")
@protocol AnalyticsServiceProtocol
- (void)setLastActivityCheckWithCompletionHandler:(void (^ _Nonnull)(BOOL, KindredCoreError * _Nullable))completionHandler;
@end

@class CoreConfiguration;
@class NSString;
@class NSURL;

SWIFT_PROTOCOL("_TtP14KindredSDKCore19ApiSettingsProtocol_")
@protocol ApiSettingsProtocol
- (void)setupWithConfiguration:(CoreConfiguration * _Nonnull)configuration;
- (NSString * _Nonnull)getBaseUrlWithPath:(NSString * _Nullable)path SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getImageUrlWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
- (NSURL * _Nullable)getImageUrlWithPath:(NSString * _Nonnull)path parameters:(NSDictionary<NSString *, NSString *> * _Nonnull)parameters SWIFT_WARN_UNUSED_RESULT;
- (CoreConfiguration * _Nullable)getCoreConfiguration SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP14KindredSDKCore29AuthenticationServiceProtocol_")
@protocol AuthenticationServiceProtocol
- (void)authenticateSDKWithCompletionHandler:(void (^ _Nonnull)(BOOL, KindredCoreError * _Nullable))completionHandler;
@end


SWIFT_CLASS("_TtC14KindredSDKCore7Charity")
@interface Charity : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14KindredSDKCore15CoreAppSettings")
@interface CoreAppSettings : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14KindredSDKCore17CoreConfiguration")
@interface CoreConfiguration : NSObject
- (nonnull instancetype)init;
@end

@class NSData;

SWIFT_PROTOCOL("_TtP14KindredSDKCore20CoreSettingsProtocol_")
@protocol CoreSettingsProtocol <NSObject>
- (void)saveSettingWithObj:(id _Nonnull)obj key:(NSString * _Nonnull)key;
- (NSString * _Nonnull)getSettingWithKey:(NSString * _Nonnull)key defaultValue:(NSString * _Nullable)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getSettingBoolWithKey:(NSString * _Nonnull)key defaultValue:(BOOL)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getSettingIntWithKey:(NSString * _Nonnull)key defaultValue:(NSInteger)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nonnull)getSettingArrayWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)getSettingDataWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)removeSettingsWithKey:(NSString * _Nonnull)key;
- (void)setUserIdWithUserId:(NSString * _Nonnull)userId;
- (NSString * _Nullable)getUserIdAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getUserCurrency SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getUserCurrencyFromLocale SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getUserCountry SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getUserCountryByTelephony SWIFT_WARN_UNUSED_RESULT;
- (void)setStandardUserCountry;
- (void)setStandardUserCurrency;
- (NSString * _Nonnull)dealsSearchRequest SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)activateDealRequest SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isSDKMode SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDeviceId SWIFT_WARN_UNUSED_RESULT;
- (void)setCouponsOnlyWithValue:(BOOL)value;
- (BOOL)isCouponsOnly SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isValueSetWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14KindredSDKCore12CoreSettings")
@interface CoreSettings : NSObject <CoreSettingsProtocol>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)saveSettingWithObj:(id _Nonnull)obj key:(NSString * _Nonnull)key;
- (NSString * _Nonnull)getSettingWithKey:(NSString * _Nonnull)key defaultValue:(NSString * _Nullable)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getSettingBoolWithKey:(NSString * _Nonnull)key defaultValue:(BOOL)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getSettingIntWithKey:(NSString * _Nonnull)key defaultValue:(NSInteger)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nonnull)getSettingArrayWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)getSettingDataWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)removeSettingsWithKey:(NSString * _Nonnull)key;
- (void)setUserIdWithUserId:(NSString * _Nonnull)userId;
- (NSString * _Nullable)getUserIdAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getUserCurrency SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getUserCurrencyFromLocale SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getUserCountry SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getUserCountryByTelephony SWIFT_WARN_UNUSED_RESULT;
- (void)setStandardUserCurrency;
- (void)setStandardUserCountry;
- (NSString * _Nonnull)dealsSearchRequest SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)activateDealRequest SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isSDKMode SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isCouponsOnly SWIFT_WARN_UNUSED_RESULT;
- (void)setCouponsOnlyWithValue:(BOOL)value;
- (NSString * _Nullable)getDeviceId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isValueSetWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC14KindredSDKCore11CouponCodes")
@interface CouponCodes : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
@property (nonatomic, readonly, copy) NSString * _Nonnull summary;
@end


SWIFT_CLASS("_TtC14KindredSDKCore4Deal")
@interface Deal : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull dealId;
@property (nonatomic, readonly, copy) NSString * _Nonnull storeName;
@property (nonatomic, readonly) float cashback;
@property (nonatomic, readonly, copy) NSString * _Nonnull cashbackType;
@property (nonatomic, readonly, copy) NSString * _Nullable currency;
@property (nonatomic, readonly, copy) NSString * _Nullable logo;
@property (nonatomic, readonly, copy) NSArray<CouponCodes *> * _Nullable codes;
@end


SWIFT_CLASS("_TtC14KindredSDKCore9DealClick")
@interface DealClick : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable link;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP14KindredSDKCore20DealsServiceProtocol_")
@protocol DealsServiceProtocol <NSObject>
- (void)searchForDealsWithSearchTerm:(NSString * _Nonnull)searchTerm completionHandler:(void (^ _Nonnull)(NSArray<Deal *> * _Nullable, KindredCoreError * _Nullable))completionHandler;
- (void)getDealUniqueTrackingLinkFor:(NSString * _Nonnull)dealID analytics:(NSDictionary<NSString *, id> * _Nonnull)analytics completionHandler:(void (^ _Nonnull)(DealClick * _Nullable, KindredCoreError * _Nullable))completionHandler;
- (void)getDealUniqueTrackingLinkFor:(NSString * _Nonnull)dealID completionHandler:(void (^ _Nonnull)(DealClick * _Nullable, KindredCoreError * _Nullable))completionHandler;
@end


SWIFT_CLASS("_TtC14KindredSDKCore12DealsService")
@interface DealsService : NSObject <DealsServiceProtocol>
- (void)searchForDealsWithSearchTerm:(NSString * _Nonnull)searchTerm completionHandler:(void (^ _Nonnull)(NSArray<Deal *> * _Nullable, KindredCoreError * _Nullable))completionHandler;
/// Activate deal and return deal unique tracking Url
/// \param params <code>Request<DealClickResponse></code>
///
///
/// returns:
/// <code>DealClick</code>, ’<code>KindredCoreError?</code>
- (void)getDealUniqueTrackingLinkFor:(NSString * _Nonnull)dealID analytics:(NSDictionary<NSString *, id> * _Nonnull)analytics completionHandler:(void (^ _Nonnull)(DealClick * _Nullable, KindredCoreError * _Nullable))completionHandler;
- (void)getDealUniqueTrackingLinkFor:(NSString * _Nonnull)dealID completionHandler:(void (^ _Nonnull)(DealClick * _Nullable, KindredCoreError * _Nullable))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class UIImage;

SWIFT_CLASS("_TtC14KindredSDKCore15ImageDownloader")
@interface ImageDownloader : NSObject
+ (UIImage * _Nullable)downloadImageWithUrl:(NSURL * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol OneTimeLinkServiceProtocol;
@protocol UserServiceProtocol;

SWIFT_CLASS("_TtC14KindredSDKCore12InjectedCore")
@interface InjectedCore : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <CoreSettingsProtocol> _Nonnull settings;)
+ (id <CoreSettingsProtocol> _Nonnull)settings SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <DealsServiceProtocol> _Nonnull dealsService;)
+ (id <DealsServiceProtocol> _Nonnull)dealsService SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <OneTimeLinkServiceProtocol> _Nonnull oneTimeLinkService;)
+ (id <OneTimeLinkServiceProtocol> _Nonnull)oneTimeLinkService SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <UserServiceProtocol> _Nonnull userService;)
+ (id <UserServiceProtocol> _Nonnull)userService SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <AuthenticationServiceProtocol> _Nonnull authenticationService;)
+ (id <AuthenticationServiceProtocol> _Nonnull)authenticationService SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <AnalyticsServiceProtocol> _Nonnull analyticsService;)
+ (id <AnalyticsServiceProtocol> _Nonnull)analyticsService SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <ApiSettingsProtocol> _Nonnull apiSettings;)
+ (id <ApiSettingsProtocol> _Nonnull)apiSettings SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ErrorType : NSInteger;

SWIFT_CLASS("_TtC14KindredSDKCore16KindredCoreError")
@interface KindredCoreError : NSObject
@property (nonatomic, readonly) enum ErrorType errorType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithErrorType:(enum ErrorType)errorType;
@end

typedef SWIFT_ENUM(NSInteger, ErrorType, open) {
  ErrorTypeOneTimeIdError = 0,
  ErrorTypeSdkAuthenticationError = 1,
  ErrorTypeDealSearchError = 2,
  ErrorTypeDealActivationError = 3,
  ErrorTypeSetAnalyticsCheckError = 4,
  ErrorTypeSetCharityError = 5,
  ErrorTypeNoUserId = 6,
  ErrorTypeNoError = 7,
};


@interface KindredCoreError (SWIFT_EXTENSION(KindredSDKCore))
@property (nonatomic, readonly, copy) NSString * _Nullable errorDescription;
@end


SWIFT_PROTOCOL("_TtP14KindredSDKCore26OneTimeLinkServiceProtocol_")
@protocol OneTimeLinkServiceProtocol
- (void)getOnetimeAuthenticationIdWithCompletionHandler:(void (^ _Nonnull)(NSString * _Nullable, KindredCoreError * _Nullable))completionHandler;
@end


SWIFT_PROTOCOL("_TtP14KindredSDKCore19UserServiceProtocol_")
@protocol UserServiceProtocol
- (void)setDonationCharityWithCharityID:(NSString * _Nonnull)charityID charityShare:(NSInteger)charityShare completionHandler:(void (^ _Nonnull)(BOOL, KindredCoreError * _Nullable))completionHandler;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef KINDREDSDKCORE_SWIFT_H
#define KINDREDSDKCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="KindredSDKCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC14KindredSDKCore9Analytics")
@interface Analytics : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
@class KindredCoreError;

SWIFT_PROTOCOL("_TtP14KindredSDKCore24AnalyticsServiceProtocol_")
@protocol AnalyticsServiceProtocol
- (void)setLastActivityCheckWithCompletionHandler:(void (^ _Nonnull)(BOOL, KindredCoreError * _Nullable))completionHandler;
@end

@class CoreConfiguration;
@class NSString;
@class NSURL;

SWIFT_PROTOCOL("_TtP14KindredSDKCore19ApiSettingsProtocol_")
@protocol ApiSettingsProtocol
- (void)setupWithConfiguration:(CoreConfiguration * _Nonnull)configuration;
- (NSString * _Nonnull)getBaseUrlWithPath:(NSString * _Nullable)path SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getImageUrlWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
- (NSURL * _Nullable)getImageUrlWithPath:(NSString * _Nonnull)path parameters:(NSDictionary<NSString *, NSString *> * _Nonnull)parameters SWIFT_WARN_UNUSED_RESULT;
- (CoreConfiguration * _Nullable)getCoreConfiguration SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP14KindredSDKCore29AuthenticationServiceProtocol_")
@protocol AuthenticationServiceProtocol
- (void)authenticateSDKWithCompletionHandler:(void (^ _Nonnull)(BOOL, KindredCoreError * _Nullable))completionHandler;
@end


SWIFT_CLASS("_TtC14KindredSDKCore7Charity")
@interface Charity : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14KindredSDKCore15CoreAppSettings")
@interface CoreAppSettings : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14KindredSDKCore17CoreConfiguration")
@interface CoreConfiguration : NSObject
- (nonnull instancetype)init;
@end

@class NSData;

SWIFT_PROTOCOL("_TtP14KindredSDKCore20CoreSettingsProtocol_")
@protocol CoreSettingsProtocol <NSObject>
- (void)saveSettingWithObj:(id _Nonnull)obj key:(NSString * _Nonnull)key;
- (NSString * _Nonnull)getSettingWithKey:(NSString * _Nonnull)key defaultValue:(NSString * _Nullable)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getSettingBoolWithKey:(NSString * _Nonnull)key defaultValue:(BOOL)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getSettingIntWithKey:(NSString * _Nonnull)key defaultValue:(NSInteger)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nonnull)getSettingArrayWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)getSettingDataWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)removeSettingsWithKey:(NSString * _Nonnull)key;
- (void)setUserIdWithUserId:(NSString * _Nonnull)userId;
- (NSString * _Nullable)getUserIdAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getUserCurrency SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getUserCurrencyFromLocale SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getUserCountry SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getUserCountryByTelephony SWIFT_WARN_UNUSED_RESULT;
- (void)setStandardUserCountry;
- (void)setStandardUserCurrency;
- (NSString * _Nonnull)dealsSearchRequest SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)activateDealRequest SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isSDKMode SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDeviceId SWIFT_WARN_UNUSED_RESULT;
- (void)setCouponsOnlyWithValue:(BOOL)value;
- (BOOL)isCouponsOnly SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isValueSetWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14KindredSDKCore12CoreSettings")
@interface CoreSettings : NSObject <CoreSettingsProtocol>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)saveSettingWithObj:(id _Nonnull)obj key:(NSString * _Nonnull)key;
- (NSString * _Nonnull)getSettingWithKey:(NSString * _Nonnull)key defaultValue:(NSString * _Nullable)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getSettingBoolWithKey:(NSString * _Nonnull)key defaultValue:(BOOL)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getSettingIntWithKey:(NSString * _Nonnull)key defaultValue:(NSInteger)defaultValue SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nonnull)getSettingArrayWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)getSettingDataWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)removeSettingsWithKey:(NSString * _Nonnull)key;
- (void)setUserIdWithUserId:(NSString * _Nonnull)userId;
- (NSString * _Nullable)getUserIdAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getUserCurrency SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getUserCurrencyFromLocale SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getUserCountry SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getUserCountryByTelephony SWIFT_WARN_UNUSED_RESULT;
- (void)setStandardUserCurrency;
- (void)setStandardUserCountry;
- (NSString * _Nonnull)dealsSearchRequest SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)activateDealRequest SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isSDKMode SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isCouponsOnly SWIFT_WARN_UNUSED_RESULT;
- (void)setCouponsOnlyWithValue:(BOOL)value;
- (NSString * _Nullable)getDeviceId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isValueSetWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC14KindredSDKCore11CouponCodes")
@interface CouponCodes : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull code;
@property (nonatomic, readonly, copy) NSString * _Nonnull summary;
@end


SWIFT_CLASS("_TtC14KindredSDKCore4Deal")
@interface Deal : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull dealId;
@property (nonatomic, readonly, copy) NSString * _Nonnull storeName;
@property (nonatomic, readonly) float cashback;
@property (nonatomic, readonly, copy) NSString * _Nonnull cashbackType;
@property (nonatomic, readonly, copy) NSString * _Nullable currency;
@property (nonatomic, readonly, copy) NSString * _Nullable logo;
@property (nonatomic, readonly, copy) NSArray<CouponCodes *> * _Nullable codes;
@end


SWIFT_CLASS("_TtC14KindredSDKCore9DealClick")
@interface DealClick : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable link;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP14KindredSDKCore20DealsServiceProtocol_")
@protocol DealsServiceProtocol <NSObject>
- (void)searchForDealsWithSearchTerm:(NSString * _Nonnull)searchTerm completionHandler:(void (^ _Nonnull)(NSArray<Deal *> * _Nullable, KindredCoreError * _Nullable))completionHandler;
- (void)getDealUniqueTrackingLinkFor:(NSString * _Nonnull)dealID analytics:(NSDictionary<NSString *, id> * _Nonnull)analytics completionHandler:(void (^ _Nonnull)(DealClick * _Nullable, KindredCoreError * _Nullable))completionHandler;
- (void)getDealUniqueTrackingLinkFor:(NSString * _Nonnull)dealID completionHandler:(void (^ _Nonnull)(DealClick * _Nullable, KindredCoreError * _Nullable))completionHandler;
@end


SWIFT_CLASS("_TtC14KindredSDKCore12DealsService")
@interface DealsService : NSObject <DealsServiceProtocol>
- (void)searchForDealsWithSearchTerm:(NSString * _Nonnull)searchTerm completionHandler:(void (^ _Nonnull)(NSArray<Deal *> * _Nullable, KindredCoreError * _Nullable))completionHandler;
/// Activate deal and return deal unique tracking Url
/// \param params <code>Request<DealClickResponse></code>
///
///
/// returns:
/// <code>DealClick</code>, ’<code>KindredCoreError?</code>
- (void)getDealUniqueTrackingLinkFor:(NSString * _Nonnull)dealID analytics:(NSDictionary<NSString *, id> * _Nonnull)analytics completionHandler:(void (^ _Nonnull)(DealClick * _Nullable, KindredCoreError * _Nullable))completionHandler;
- (void)getDealUniqueTrackingLinkFor:(NSString * _Nonnull)dealID completionHandler:(void (^ _Nonnull)(DealClick * _Nullable, KindredCoreError * _Nullable))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class UIImage;

SWIFT_CLASS("_TtC14KindredSDKCore15ImageDownloader")
@interface ImageDownloader : NSObject
+ (UIImage * _Nullable)downloadImageWithUrl:(NSURL * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol OneTimeLinkServiceProtocol;
@protocol UserServiceProtocol;

SWIFT_CLASS("_TtC14KindredSDKCore12InjectedCore")
@interface InjectedCore : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <CoreSettingsProtocol> _Nonnull settings;)
+ (id <CoreSettingsProtocol> _Nonnull)settings SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <DealsServiceProtocol> _Nonnull dealsService;)
+ (id <DealsServiceProtocol> _Nonnull)dealsService SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <OneTimeLinkServiceProtocol> _Nonnull oneTimeLinkService;)
+ (id <OneTimeLinkServiceProtocol> _Nonnull)oneTimeLinkService SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <UserServiceProtocol> _Nonnull userService;)
+ (id <UserServiceProtocol> _Nonnull)userService SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <AuthenticationServiceProtocol> _Nonnull authenticationService;)
+ (id <AuthenticationServiceProtocol> _Nonnull)authenticationService SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <AnalyticsServiceProtocol> _Nonnull analyticsService;)
+ (id <AnalyticsServiceProtocol> _Nonnull)analyticsService SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id <ApiSettingsProtocol> _Nonnull apiSettings;)
+ (id <ApiSettingsProtocol> _Nonnull)apiSettings SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ErrorType : NSInteger;

SWIFT_CLASS("_TtC14KindredSDKCore16KindredCoreError")
@interface KindredCoreError : NSObject
@property (nonatomic, readonly) enum ErrorType errorType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithErrorType:(enum ErrorType)errorType;
@end

typedef SWIFT_ENUM(NSInteger, ErrorType, open) {
  ErrorTypeOneTimeIdError = 0,
  ErrorTypeSdkAuthenticationError = 1,
  ErrorTypeDealSearchError = 2,
  ErrorTypeDealActivationError = 3,
  ErrorTypeSetAnalyticsCheckError = 4,
  ErrorTypeSetCharityError = 5,
  ErrorTypeNoUserId = 6,
  ErrorTypeNoError = 7,
};


@interface KindredCoreError (SWIFT_EXTENSION(KindredSDKCore))
@property (nonatomic, readonly, copy) NSString * _Nullable errorDescription;
@end


SWIFT_PROTOCOL("_TtP14KindredSDKCore26OneTimeLinkServiceProtocol_")
@protocol OneTimeLinkServiceProtocol
- (void)getOnetimeAuthenticationIdWithCompletionHandler:(void (^ _Nonnull)(NSString * _Nullable, KindredCoreError * _Nullable))completionHandler;
@end


SWIFT_PROTOCOL("_TtP14KindredSDKCore19UserServiceProtocol_")
@protocol UserServiceProtocol
- (void)setDonationCharityWithCharityID:(NSString * _Nonnull)charityID charityShare:(NSInteger)charityShare completionHandler:(void (^ _Nonnull)(BOOL, KindredCoreError * _Nullable))completionHandler;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
